### ISSUE TITLE
Android Q API 28 ERROR: No Activity found to handle Intent { act=com.android.credentials.UNLOCK } 

### ISSUE THREAD

**Issue by gvsrinivas9** [Crypho/cordova-plugin-secure-storage#169] opened 2019-03-26 04:45 UTC
Hi, We are getting ActivityNotFoundException when we do initialize the plugin.
Could you check and let us know.

**Device Details:** 
"DeviceModel": "Pixel",
"DeviceSystemName": "Android",
"DeviceSystemVersion": "28"
"OS":"Android Q"

**Error Log:**
E/SecureStorage: SecureStorage Exception android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.credentials.UNLOCK }

03-26 11:42:14.343 10914-10914/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                  PID: 10914
                                                   android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.credentials.UNLOCK }
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2047)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1705)
                                                       at android.app.Activity.startActivityForResult(Activity.java:5054)
                                                       at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:342)
                                                       at android.app.Activity.startActivityForResult(Activity.java:5012)
                                                       at android.app.Activity.startActivity(Activity.java:5383)
                                                       at android.app.Activity.startActivity(Activity.java:5351)
                                                       at com.crypho.plugins.SecureStorage.startActivity(SecureStorage.java:239)
                                                       at com.crypho.plugins.SecureStorage.access$600(SecureStorage.java:20)
                                                       at com.crypho.plugins.SecureStorage$6.run(SecureStorage.java:229)
                                                       at android.os.Handler.handleCallback(Handler.java:873)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:209)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7021)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)

and 

**KeyStore exception**
  android.os.ServiceSpecificException:  (code 7)
  at android.os.Parcel.createException(Parcel.java:2073)
                                                                        at android.os.Parcel.readException(Parcel.java:2027)
                                                                        at android.os.Parcel.readException(Parcel.java:1977)
                                                                        at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:977)
                                                                        at android.security.KeyStore.get(KeyStore.java:234)
                                                                        at android.security.KeyStore.get(KeyStore.java:223)
                                                                        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
                                                                        at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
                                                                        at java.security.KeyStore.getEntry(KeyStore.java:1560)
                                                                        at com.crypho.plugins.RSA.getKeyStoreEntry(RSA.java:87)
                                                                        at com.crypho.plugins.RSA.isEntryAvailable(RSA.java:77)
                                                                        at com.crypho.plugins.SecureStorage.execute(SecureStorage.java:94)
                                                                        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
                                                                        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                                                                        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
                                                                        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
                                                                        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
                                                                        at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                        at android.os.MessageQueue.next(MessageQueue.java:327)
                                                                        at android.os.Looper.loop(Looper.java:169)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:67)

Thanks

**Comment by yoavbar** [comment] 2019-04-02 12:46
+1

**Comment by Adza93** [comment] 2019-06-10 08:30
+1, anyone having a clue how to solve this issue?

**Comment by scotthmusson** [comment] 2019-06-20 12:42
+1 hoping to find a proper solution and a maintained plugin

**Comment by nabil-nuvolo** [comment] 2019-06-25 18:43
Also seeing this when testing our app against API29

**Comment by xDAnkit** [comment] 2019-06-26 10:41
Hey guys, is there update on raised concern. I'm also getting the similar issue when testing against API 29 ,

**Comment by matthewh1209** [comment] 2019-06-27 15:57
+1, This plugin is an integral piece to our app. I'm hoping that this issue can be resolved quickly.

**Comment by ggozad** [comment] 2019-06-27 16:02
Hey there. I am sorry to disappoint, but as in the README, this plugin is no longer maintained. 
I have tried to get to contact with ionic from where most of you come from but I haven't heard back from them.

I am afraid neither I or any of the other maintainers of secure-storage have the time to put effort in this. So you guys should fork and continue development independently.

**Comment by ggozad** [comment] 2019-06-27 16:05
The plugin is no-longer maintained closing all issues that are not going to be resolved.

**Closed by ggozad** 2019-06-27 16:05 UTC

**Comment by katk0smos** [comment] 2019-06-28 19:09
Any alternatives? @ggozad

**Comment by ggozad** [comment] 2019-06-28 19:18
Well like I said ionic or someone else will hopefully step in and pick this up.

**Comment by Adza93** [comment] 2019-06-28 19:21
I am looking on how to fix this issue. Hopefully we can have some bugfix but the problem is with this credentials activity. It looks like Android 10 completely removed it but nothing can be found about this online. 
Does anyone have any idea if this activity just changed name? And what that name would be?

**Comment by kmlzjc** [comment] 2019-07-02 10:04
Hello @Adza93. Have you been able to find any solution?

**Comment by Adza93** [comment] 2019-07-04 07:50
@kmlzjc  unfortunatelly not yet. i am trying to get out any answer from Google developers if there is any alternative to com.android.credentials.UNLOCK intent. So far, no one is responding. 

It is shame that they are just like that removing one of those security features that you use during the years in application, as we are using now.

**Comment by jfernandezgersol** [comment] 2019-07-04 09:54
Hi @Adza93, I am in the same situation. It seems that the com.android.credentials.UNLOCK was somehow never officially defined in the documentation (hidden feature). I am trying to find a parallel way to get a list with the unofficial intents but it seems to be complicated. I found info about some people trying to dump logs about the broadcast messages being sent in Android devices. Maybe could be a potential approach to capture the new name (if it was not removed/completely changed but renamed). I hope, we can find a solution soon. 

I am trying to find an alternative plugin too, but no luck until now. Maybe with this new introduced feature in Android Q (https://android-developers.googleblog.com/2019/04/android-q-scoped-storage-best-practices.html), it is not anymore necessary to have a lock pattern/pin to encrypt the info and call the unlock intent but it would mean, a new implementation would be required for Android.

It appears to exist another thread in the Ionic forums regarding this topic:

https://forum.ionicframework.com/t/ionic-native-secure-storage-not-working-on-android-q/167386

Anyway I hope we could get some feedback from the Google developers soon. Please keep us informed in case you got an answer from them.

Thank you in advance!

**Comment by xDAnkit** [comment] 2019-07-04 11:25
Hello everyone, We recently found one solution for addressing this issue. Tested it on API-29/28 and the good news is, that everything is working fine. Currently we are testing it amongst all android versions to make the code compatible throughout all available platforms. Also working on cleaning the code a bit.

Watch this space for more for a working solution.


```
// Meanwhile can someone explain what is code is doing 
// https://github.com/Crypho/cordova-plugin-secure-storage/blob/master/src/android/SecureStorage.java#L105
 else if (!RSA.isEntryAvailable(alias)) {
      initContext = callbackContext;
      unlockCredentials();
 }
```

**Comment by jfernandezgersol** [comment] 2019-07-04 14:45
Cool @xDAnkit I will check it on Monday. Thanks. Further infos I collected:

The main problem as we know is related with the Intent "com.android.credentials.UNLOCK". The plugin is calling it because a lock mechanism is required in the Android part to be able to encrypt the information in the storage (the user credentials are used to encrypt the AES key that encrypts the information).

After further research, it seems that the Intent was never be exposed officially in the API SDK. After Android Oreo it was marked as unsupported for App usage with the decorator @UnsupportedAppUsage. During the release of Android Q was added to a greylist called "hiddenapi-greylist-max-o.txt". In this file are all non-SDK elements defined in order to be avoid its consumption after Android Oreo (API 27) but the documentatiAufzählungon says that if the app targets one API same or less than 27 (Oreo), the API should be accessible. 
https://stackoverflow.com/questions/54565330/will-apis-in-hiddenapi-greylist-max-o-work-in-android-pie
https://developer.android.com/preview/non-sdk-q

To check this information, I cloned the Android AOSP source code (git clone https://github.com/aosp-mirror/platform_frameworks_base.git)
There is a tag called "android-q-preview-4", in which the file "hiddenapi-greylist-max-o.txt" can be checked and where the "com.android.credentials.UNLOCK" is not present.
There is a tag called ""android-o-preview-4" and "android-q-preview-4", in which the file "hiddenapi-greylist-max-o.txt" can be checked and where the "com.android.credentials.UNLOCK" is not present.
I have modified in the code of the plugin the call to the Intent to be "android.credentials.UNLOCK" instead of "com.android.credentials.UNLOCK" (because other Intents were defined so) and it hasn't crashed but I am not sure if it is saving the information encrypted.

**Comment by jfernandezgersol** [comment] 2019-07-08 10:56
Hi @xDAnkit  Have you done any progress? Could you indicate how have you solved it?  Thank you very much in advance.

**Comment by xDAnkit** [comment] 2019-07-08 11:22
Hey @jfernandezgersol we are finalising the testing with multiple Android platform. You can expect the update either today or latest by tomorrow.

**Comment by xDAnkit** [comment] 2019-07-08 14:09
Hey @jfernandezgersol  - Please find the details below.

After doing a research and testing with multiple Android API variants. I have found following things related to this issue. hence, to avoid app crashes modified few code mentioned below to support API28/29. Also gone through your comments and provided documentation and found that the **android.credentials.UNLOCK** is limited to old API variants.

**Working Plugin Link** - [Updated Cordova Secure Storage Plugin](https://github.com/xDAnkit/cordova-plugin-secure-storage)

I have made couple of changes in **"SecureStorage.java"** file for following reason.

- API 29  No longer supports com.android.credentials.UNLOCK
- You no longer need com.android.credentials.UNLOCK while dealing with API29
- API above 28 needs to handled separately
- Some people mentioned that they're facing issue on API-28, That's why i've added the support for >= API 28
- android.credentials.UNLOCK can only be used before android android lollipop, hence skipped


```js
//Replaced this code

if (!isDeviceSecure()) {
  Log.e(TAG, MSG_DEVICE_NOT_SECURE);
    callbackContext.error(MSG_DEVICE_NOT_SECURE);
} else if (!RSA.isEntryAvailable(alias)) {
    initContext = callbackContext;
    unlockCredentials();
} else {
    initSuccess(callbackContext);
}
return true;


// With the following below

// To check whether the device is secure
if (!isDeviceSecure()) {
    Log.i("INFO","Device is not secure");
    Log.e(TAG, MSG_DEVICE_NOT_SECURE);
    callbackContext.error(MSG_DEVICE_NOT_SECURE);
    return true;
}

// To check whether the device is matching API 28 or above i.e not longer support for com.android.credentials.UNLOCK
// Hence init success callback
if (MATCHES_ANDROID_API_28) {
    Log.i("INFO","Device is beyond API28");
    initSuccess(callbackContext);
    return true;
}

Log.i("INFO","Device is below API28, hence calling unlockCreds");
// For lower devices than MATCHES_ANDROID_API_28, Init callback context and Dispatch com.android.credentials.UNLOCK
initContext = callbackContext;
unlockCredentials();
return true;

```

```js
// Replaced this with
public void run() {
    Intent intent = new Intent("com.android.credentials.UNLOCK");
    startActivity(intent);
}

// This one
public void run() {
    // Wrapping it inside try catch block, to avoid application crashes and replacing hardocoded string with ACTION_UNLOCK
    try {
        Intent intent = new Intent(ACTION_UNLOCK);
        startActivity(intent);
    } catch (ActivityNotFoundException e) {
        Log.e(TAG, "No activity found :", e);
    }
}
```

Also modified few small things that can be reviewed under following commits i.e package version and variable names.
https://github.com/xDAnkit/cordova-plugin-secure-storage/commit/1810477e59b0080f08ea3377420b908e551fd690
https://github.com/xDAnkit/cordova-plugin-secure-storage/commit/ee8f8f30ec6e522055f74e739759164da9c7ac20
https://github.com/xDAnkit/cordova-plugin-secure-storage/commit/1fc8088e64b5d086a2f9e43fc8178b2108f330eb


Tested it on Multiple platforms i.e. Android API 27,28,29 Including x86, x64_x86

Open for feedbacks and reviews.

**Comment by jfernandezgersol** [comment] 2019-07-08 14:32
Hi @xDAnkit  I have reached more or less the same conclusions as you can see in the following fork: https://github.com/jfernandezgersol/cordova-plugin-secure-storage/commit/327380799eab0564a34294d6db5e93e36daa3b59 
Anyway your solution seems to be more complete :) It would be great if your changes could be released as new version. I think it would be very important for the Ionic community too. Thanks again!

**Comment by xDAnkit** [comment] 2019-07-09 10:45
@jfernandezgersol  - Glad that you liked my solution.

@ggozad - Would to like to send me a pull request for merging the following updated code to your master branch as @jfernandezgersol  mentioned?

**Comment by mibrito707** [comment] 2019-07-09 17:30
In an effort to keep this project alive, I also tried to get a working solution in the following fork: https://github.com/mibrito707/cordova-plugin-secure-storage 
**Reviewers, comments and PR** are welcome and I'll be more than happy to create a pull request to maintain this plugin (@ggozad) up to date since it's currently used in the latest Ionic version (my case currently).

I test it in a variety of Android phones with different API versions and it's working as expected.
Some changes included are:
- Remove the use of deprecated/private API (com.android.credentials.UNLOCK). Use [Settings.ACTION_SECURITY_SETTINGS](https://developer.android.com/reference/android/provider/Settings#ACTION_SECURITY_SETTINGS) instead.
- Use [KeyGenParameterSpec](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder), instead of deprecated [KeyPairGeneratorSpec](https://developer.android.com/reference/android/security/KeyPairGeneratorSpec.Builder.html), as recommended for API >= 23 while maintaining backwards compatibility.
- Use [KeyguardManager.createConfirmDeviceCredentialIntent](https://developer.android.com/reference/android/app/KeyguardManager.html#createConfirmDeviceCredentialIntent(java.lang.CharSequence,%20java.lang.CharSequence)) to ask User's credentials only when needed. See [#163](https://github.com/Crypho/cordova-plugin-secure-storage/issues/163#issuecomment-465282967) for more info.
- [New Android options](https://github.com/mibrito707/cordova-plugin-secure-storage#android-init-options) to configure new API requirements.
- Brush up unused imports, variable names and code format.

Ionic users can eaily use and test this fork by:
1. Removing `plugins` and `platform` folders.
2.  Changing your `cordova-plugin-secure-storage` dependency in `package.json`:
```js
dependencies: {
....
"cordova-plugin-secure-storage": "git://github.com/mibrito707/cordova-plugin-secure-storage.git#v4.0.0-beta",
....
}
```
2. Removing `plugins` and `platform` folders.
3. Run `ionic cordova run android -l -d`

Thanks for this awesome plugin.

**Comment by paamrutk** [comment] 2019-07-24 06:31
@mibrito707 Thank you for your support.
Can you please tell by when this update will be available officially.

**Comment by rajashekaranugu** [comment] 2019-07-24 14:37
@mibrito707, this solved our issue with Android Q (pixel 3). Thank you for the support. when are you planning to go for live Also can you please let us know how can we get notified upon live.

Apart from this is there any official site where we can track for Android Q release dates? some site states they may go live in August. Any input is much appreciated

**Comment by orest** [comment] 2019-07-25 14:31
I'm having this issue when building/running. Can you please let me know how to go around it

Error: xxx/Mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
xxx/Mobile/platforms/android/src/com/crypho/plugins/SecureStorage.java:229: error: local variable title is accessed from within inner class; needs to be declared final
                Intent intent = keyguardManager.createConfirmDeviceCredentialIntent(title, description);
                                                                                    ^
xxx/Mobile/platforms/android/src/com/crypho/plugins/SecureStorage.java:229: error: local variable description is accessed from within inner class; needs to be declared final
                Intent intent = keyguardManager.createConfirmDeviceCredentialIntent(title, description);
                                                                                           ^
xxx/Mobile/platforms/android/src/com/crypho/plugins/SecureStorage.java:249: error: local variable userAuthenticationValidityDuration is accessed from within inner class; needs to be declared final
                        RSA.createKeyPair(getContext(), alias, userAuthenticationValidityDuration);
 
Thank you!

**Comment by shanlin2dltk** [comment] 2019-07-30 18:03
@mibrito707  I experienced an issue with the plugin.  Here are the steps to replicate: using https://github.com/mibrito707/cordova-plugin-secure-storage I built a cordova app that allows users setting up a PIN, and install on android 9.  The app works fine on android 9.  After I upgrade the device OS to android 10 (also called android Q), it cannot retrieve the PIN information from local storage any more.  Have you tested this scenario?  Thanks.

**Comment by mibrito707** [comment] 2019-07-30 20:49
> @mibrito707 Thank you for your support.
> Can you please tell by when this update will be available officially.

@paamrutk IDK if we'll able to release and maintain a new version on this Github repo since the authors don't respond to my requests to maintain the original plugin. In the meantime tough I just updated https://github.com/mibrito707/cordova-plugin-secure-storage syncronizing versions and **officially** releasing v4.0.1

**Comment by mibrito707** [comment] 2019-07-30 20:55
> @mibrito707, this solved our issue with Android Q (pixel 3). Thank you for the support. when are you planning to go for live Also can you please let us know how can we get notified upon live.
> 
@rajashekaranugu  Thank you for the feedback, version 4.0.1 is released here https://github.com/mibrito707/cordova-plugin-secure-storage since it's working great so far for my team.

> Apart from this is there any official site where we can track for Android Q release dates? some site states they may go live in August. Any input is much appreciated

There is no official date yet for Android Q release but should be pretty soon, probably by the end of August as you mentioned. I follow this to be up to date: https://developer.android.com/preview

**Comment by mibrito707** [comment] 2019-07-30 20:57
> I'm having this issue when building/running. Can you please let me know how to go around it
> 
> Error: xxx/Mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
> xxx/Mobile/platforms/android/src/com/crypho/plugins/SecureStorage.java:229: error: local variable title is accessed from within inner class; needs to be declared final
> Intent intent = keyguardManager.createConfirmDeviceCredentialIntent(title, description);
> ^
> xxx/Mobile/platforms/android/src/com/crypho/plugins/SecureStorage.java:229: error: local variable description is accessed from within inner class; needs to be declared final
> Intent intent = keyguardManager.createConfirmDeviceCredentialIntent(title, description);
> ^
> xxx/Mobile/platforms/android/src/com/crypho/plugins/SecureStorage.java:249: error: local variable userAuthenticationValidityDuration is accessed from within inner class; needs to be declared final
> RSA.createKeyPair(getContext(), alias, userAuthenticationValidityDuration);
> 
> Thank you!

Hey @orest, Thanks for the feedback, I'll take a look into this but can you please create an issue here: https://github.com/mibrito707/cordova-plugin-secure-storage so we can keep track of it and have a different thread.

**Comment by mibrito707** [comment] 2019-07-30 20:58
> @mibrito707 I experienced an issue with the plugin. Here are the steps to replicate: using https://github.com/mibrito707/cordova-plugin-secure-storage I built a cordova app that allows users setting up a PIN, and install on android 9. The app works fine on android 9. After I upgrade the device OS to android 10 (also called android Q), it cannot retrieve the PIN information from local storage any more. Have you tested this scenario? Thanks.

Hello @shanlin2dltk, thanks for the feedback.  
I'll take a look into this but in the meantime can you please create an issue here: https://github.com/mibrito707/cordova-plugin-secure-storage so we can keep track of it and have a different thread.

**Comment by orest** [comment] 2019-07-31 00:21
@mibrito707 Thank you for looking into it. Do you think you can enable "Issues" tab on https://github.com/mibrito707/cordova-plugin-secure-storage 
Thanks again!

**Comment by ggozad** [comment] 2019-07-31 07:06
Hey @mibrito707 . I will be happy to make a note on the README about you maintaining the plugin provided you can also maintain the iOS version.
I will close this repo, please contact me directly.
