### ISSUE TITLE
Issue iOS – Failure in SecureStorage.set() The specified item allready exists in the keychain

### ISSUE THREAD

**Issue by szankelDvag** [Crypho/cordova-plugin-secure-storage#88] opened 2017-01-28 10:01 UTC
Setup:
-	Ionic@2.0.0-rc2
-	Ionic-native@2.2.3
-	Cordova@6.4.0
-	Angular@2.1.1

We are currently developing some Ionic 2 mobile application. In regards of securely storing the data throughout the application workflow, we are using your secure storage plugin to store critical data. On Android everything seems to work fine. Under iOS we often times get messages similar to: 

**The specified item allready exists in the keychain for setter
The specified item doesn’t exist in the keychain for getter and remove**

We allready attempted to check the keys before we try to get, set or remove values from the secure storage. But with no success. 

The problem mainly occurs when the app is reinstalled.

Here are some parts of our implementation:

SecureStorageService.ts – Abstracts the communication to secure storage since we are using Fallback store in case the screenlock is not activated on Android to expose some identical interface.

Get value from secure store:

```
get(key: string): Promise<any> {
  return new Promise((resolve)=> {
    this.keys().then((keys)=> {
      if (keys.indexOf(key) > -1) {
        this.store.get(
          data=> resolve(data),
          ()=> resolve(undefined),
          key)
      } else {
        resolve(undefined);
      }
    });
  });
```

Set value in secure store:

```
set(key: string, value: string): Promise<any> {
  return new Promise((resolve, reject)=> {
    this.keys().then((keys)=> {
      if (keys.indexOf(key) > -1) {
        this.remove(key).then(()=> this.store.set(resolve, reject, key, value));
      } else {
        this.store.set(resolve, reject, key, value);
      }
    })
  })
}
```

Remove value from secure store:

```
remove(key: string): Promise<any> {
  return new Promise((resolve, reject)=> {
    this.keys().then((keys)=> {
      if (keys.indexOf(key) > -1) {
        this.store.remove(resolve, reject, key);
      } else {
        reject();
      }
    });
  });
}

```
Get keys from secure store:

```
keys(): Promise<any> {
  return new Promise((resolve, reject)=> {
    this.store.keys((keys)=> resolve(keys), (error)=>reject(error));
  });
}
```

For  the create we just use something in terms of:

```
if (Device.device.platform === 'Android' || Device.device.platform === 'iOS') {
  this.store = new (<any>window).cordova.plugins.SecureStorage(successCB, errorCB);
}
```

also wrapped in a promise and with the fallback logic, I was speaking about before, in the error case.

We really would appreciate your help with that issue. Thanks a lot before and nice regards from Germany.

Sebastian

**Comment by ggozad** [comment] 2017-01-30 12:20
Hey, does the test suite runs ok with your setup?
We haven't seen this, could you try to add a failing test?

**Comment by szankelDvag** [comment] 2017-01-31 14:35
Hi ggozad,

thanks for your response. I tried the test suite and added this test:

```
  it('should be able to override a key/value', function (done) {
                spyOn(handlers, 'successHandler').and.callFake(function (res) {
                    expect(res).toEqual('bull');
                    expect(handlers.errorHandler).not.toHaveBeenCalled();
                    done();
                });
                spyOn(handlers, 'errorHandler');

                function handleError(error) {
                    console.log(error);
                    handlers.errorHandler();
                }

                function succssCB2() {
                    ss.get(handlers.successHandler, function (error) { console.log(error); handlers.errorHandler()}, 'foo')
                }

                function successCB1() {
                    ss.set(succssCB2, handleError, 'foo', 'bull')
                }

                ss = new cordova.plugins.SecureStorage(function () {
                    ss.set(successCB1, handleError , 'foo', 'bar');
                }, handlers.errorHandler, SERVICE);
            });
```

It runs fine. I also set <preference name="KeychainAccessibility" value="Always"/>

We still get that errors. It goes into that else case of the objective c implementation:

if ([query save:&error]) {
            [self successWithMessage: key : command.callbackId];
        } else {
            NSLog(@"key %s" +key);
            NSLog(@"Query account %s" +query.account);
            [self failWithMessage: @"Failure in SecureStorage.set()" : error : command.callbackId];
        }

Sometimes we also get similar errors also for remove or the get.

We already tried for example in the set to check if the item exists and remove it with the JavaScript handlers. But still have this problem. It seems like it is a sporadic problem, which not always occurs.

What can we do to fix this?

Thanks,

Sebastian

**Comment by ggozad** [comment] 2017-02-02 09:45
I am thinking that the error might have something to do either with your app or ionic or the underlying SAMKeychain we use. Could you please verify that SAMKeychain works for you? There is very little in our plugin that could cause these errors.

**Comment by szankelDvag** [comment] 2017-02-09 09:08
Hi Ggozad,

it seems like we tried to write the same key-value pair in parallel, while registering and login the user, we store username and this resulted in the problem with the set. It seems anyhow that also if we try to get and remove key that doesn't exist the plugin throws javascript exceptions.

Sebastian

**Comment by ggozad** [comment] 2017-02-09 14:04
Hey Sebastian, the exceptions are by design. Typically you will want to wrap them if you do not wish to handle them. Closing this now.

**Closed by ggozad** 2017-02-09 14:04 UTC
