### ISSUE TITLE
iOS10 Support?

### ISSUE THREAD

**Issue by briananderson1222** [Crypho/cordova-plugin-secure-storage#48] opened 2016-08-24 18:25 UTC
Curious if anyone has looked into iOS 10 support for this plugin.

I tested this out for the first time today and I am seeing this error when calling `cordovaSecureStorage.set`

```
message: "Failure in SecureStorage.set() - errSecDefault"
```

I will continue looking into this to see if I can find more information and will pass along any findings

_EDIT_: This seems to affect all setting and fetching

**Comment by briananderson1222** [comment] 2016-08-24 19:13
Apparently going into Compatibility Settings and enabling Keychain Sharing 'fixes' the issue. Haven't been doing iOS specific development for a while now so hoping that bringing this up might shed some light

**Comment by ggozad** [comment] 2016-08-25 08:33
Hey @briananderson1222! 
I haven't had a chance to look into this. I would really appreciate it if you do continue... Would you be able to make a branch updating the plugin so that I can have a look as well?

**Comment by ggozad** [comment] 2016-08-25 08:36
Also note https://github.com/soffes/SAMKeychain/issues/149

**Comment by briananderson1222** [comment] 2016-08-25 13:22
@ggozad Is there a reason the SAMKeychain code is so out of date? Also, is there a reason that 'SAM' is renamed to 'SS' or was this what the library used a year ago when this code was last updated?

**Comment by ggozad** [comment] 2016-08-25 13:25
@briananderson1222 indeed SSKeychain apparently became SAMKeychain. There's no particular reason, SSKeychain was more or less a sane simple API around keychain which is why it was used.

**Comment by briananderson1222** [comment] 2016-08-25 13:30
@ggozad Okay thanks for the background information. I'll continue looking into this as time allows and open a PR if I can get it working. Let me know if there is any other background information that may be useful

**Comment by briananderson1222** [comment] 2016-08-25 15:16
https://github.com/soffes/SAMKeychain/issues/52

https://openradar.appspot.com/27844971

**Comment by briananderson1222** [comment] 2016-08-25 15:17
I've made the upgrade to the latest version if you would like me to put up a PR for that.. unfortunately doesn't seem to fix the underlying Keychain issue on iOS10

**Comment by ggozad** [comment] 2016-09-13 20:00
Doomsday has come and gone. All seems fine here, did you encounter any trouble?

**Comment by ggozad** [comment] 2016-09-14 09:18
@briananderson1222 closing this as everything seems fine on iOS 10. If you do encounter any problems let me know and will reopen.

**Comment by fmhun** [comment] 2016-09-15 09:16
Hi @ggozad, @briananderson1222 

I still encountering a similar issue on iphone 7 simulator (iOS 10), with Xcode version 8.0 (8A218a) and lastest plugin version from git master branch.

The ss.set() method returns the following error :

`message: "Failure in SecureStorage.set() - Refer to SecBase.h for description"`

Are you experiencing the same issue ?

**Comment by ggozad** [comment] 2016-09-15 09:39
Hey @fmhun /cc @briananderson1222 
I am not sure what to take from this.
Tests all pass just fine on a real device, at least on my iphone 6 running ios 10.
Tests fail on emulator both on iphone 7 and 6.

We deployed the latests successfully on our own app and have had no problems reported so far. 
This indicates that the problem is with the emulators, but of course I would like to resolve it altogether.

Would appreciate verification of tests passing on different physical devices.

**Comment by briananderson1222** [comment] 2016-09-15 13:45
My experience has been the same as @ggozad. If you do want it to work on a simulator I have had luck with enabling the 'Keychain Accessbility' Capability as mentioned in this issue: https://openradar.appspot.com/27844971. I would monitor this issue as it appears to be an issue that stems from the the simulator itself.

**Comment by ggozad** [comment] 2016-09-15 13:47
Will leave this open even if it does not affect apps in production. If something changes please report here to keep everybody in the loop.

**Comment by SharkChips** [comment] 2016-10-11 20:42
Has a resolution been reached on this issue?

**Comment by ggozad** [comment] 2016-10-11 20:43
Well everybody reported the problem only appears on the emulator and seems to be a known bug. Is this different for you?

**Comment by wh33ler** [comment] 2016-12-20 10:13
I get this error also on a device. But not directly. After a fresh install and live building on the device at some point this issue appears and from then on it doesn't work anymore. Any news on this?

**Comment by ggozad** [comment] 2016-12-22 11:34
Hey @wh33ler , sorry for the late reply, christmas and all :)
We haven't experienced this on devices yet. Could you please run the test and report the errors you get on the console, on a real device?

**Comment by jvjvjv** [comment] 2017-02-16 18:06
I actually haven't been receiving errors with this under 10.2 and 10.2.1

**Comment by ggozad** [comment] 2017-02-17 09:19
@jvjvjv yep this is indeed the case, had forgotten to come back to this.

**Closed by ggozad** 2017-02-17 09:19 UTC
