### ISSUE TITLE
App using unlockCredentials crash on Android Q

### ISSUE THREAD

**Issue by anirudhd** [Crypho/cordova-plugin-secure-storage#173] opened 2019-04-06 05:10 UTC
https://github.com/Crypho/cordova-plugin-secure-storage/blob/ad1a6beda37ac41a8c0e2c490e0525d6fc64e4e4/src/android/SecureStorage.java#L198

The plugin is using "com.android.credentials.UNLOCK" intent which was removed in Android Q. Apps running on Android Q will crash with the usage of this API. It can be reproduced easily on Q beta 1

**Comment by anirudhd** [comment] 2019-04-06 05:11
The app is using "com.android.credentials.UNLOCK intent which is removed in Q

**Comment by demetris-manikas** [comment] 2019-04-08 15:18
@anirudhd Thanks for reporting.
Closing since this is a duplicate of #169.

**Closed by demetris-manikas** 2019-04-08 15:18 UTC

**Comment by Adza93** [comment] 2019-06-10 08:09
Also having this issue. Is there any solution for this?
