### ISSUE TITLE
SecureStorage.set() not working for iOS 11.1 simulator

### ISSUE THREAD

**Issue by sagrawal31** [Crypho/cordova-plugin-secure-storage#136] opened 2017-11-11 07:00 UTC
Using **Ionic 3** and installed the latest version of this plugin and when invoking the `set` method on iOS 11.1 emulator and getting the error:

```
Error: Failure in SecureStorage.set() - One or more parameters passed to a function were not valid
```

I opened the simulator dev console and directly tried as given int the docs:

[Create a namespaced storage](https://github.com/Crypho/cordova-plugin-secure-storage#create-a-namespaced-storage)

```
var ss = new cordova.plugins.SecureStorage(
    function () { console.log('Success')},
    function (error) { console.log('Error ' + error); },
    'my_app');
```

and then

[Set a key/value in the storage](https://github.com/Crypho/cordova-plugin-secure-storage#set-a-keyvalue-in-the-storage)

```
ss.set(
    function (key) { console.log('Set ' + key); },
    function (error) { console.log('Error ' + error); },
    'mykey', 'myvalue');
```

and getting the same error.

**Comment by ggozad** [comment] 2017-11-11 19:24
Duplicate of #134

**Closed by ggozad** 2017-11-11 19:24 UTC
